version: '2'

services:
  omp.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  omp.api.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  omp.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orchid.cloud.agent:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
